skip tests

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,14 +23,14 @@ jobs:
         run: dotnet build
         working-directory: .
 
-      - name: test
-        run: |
-          dotnet test
-          if [ $? -eq 0 ]; then
-            echo TESTS PASSED
-          else
-            echo TESTS FAILED
-            exit 1
-          fi
-        working-directory: ./BlazorDiffusion.Tests
+      # - name: test
+      #   run: |
+      #     dotnet test
+      #     if [ $? -eq 0 ]; then
+      #       echo TESTS PASSED
+      #     else
+      #       echo TESTS FAILED
+      #       exit 1
+      #     fi
+      #   working-directory: ./BlazorDiffusion.Tests
 
